CREATE DATABASE IF NOT EXISTS miapp_db;

--CREATE USER IF NOT EXISTS 'miapp_user'@'%' IDENTIFIED BY 'ClaveSegura123!';
--GRANT SELECT, INSERT, UPDATE, DELETE ON miapp_db.* TO 'miapp_user'@'%';
--FLUSH PRIVILEGES;

USE miapp_db;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
